### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by Frido-Cpp** [Tomiwa-Ot/moukthar#12]
After building apk correctly an doing everything correct, my pc receives connection but client(my phone) doesn't show up in web ui

**Comment by tehseensagar** [comment]
@Tomiwa-Ot  
please fix the issue there is no connection back to web panel after apk installed.

**Comment by ayongulon** [comment]
> @Tomiwa-Ot please fix the issue there is no connection back to web panel after apk installed.

me too

**Comment by Tomiwa-Ot** [comment]
@tehseensagar @Frido-Cpp @ayongulon pull the updates, follow the installation instructions and try again.
