### ISSUE TITLE
please make a video about the installation of mokhtar

### ISSUE THREAD

**Issue by alexsw1** [Tomiwa-Ot/moukthar#15]
please make a video about the installation of mokhtar Android remote administration,
otherwise nothing is clear.

**Comment by Nishok000123** [comment]
Yeah

**Comment by mononoor** [comment]
yas. please

**Comment by Forezsty** [comment]
I'll give 15 dollars to anyone who can teach us how to installing.
tg. @sempronx

**Comment by ramzisx18** [comment]
> please make a video about the installation of mokhtar Android remote administration, otherwise nothing is clear.


I know how and I will share with you the easy way '-'

**Comment by divakarmokal2001** [comment]
please make a video about the installation

**Comment by unixpoin** [comment]
i have problem with login, no info about default credential

![image](https://github.com/Tomiwa-Ot/moukthar/assets/50932471/b085f486-62b0-4ee5-85b0-4406769cf5e6)

**Comment by vipclub88** [comment]
> i have problem with login, no info about default credential
> 
> ![image](https://private-user-images.githubusercontent.com/50932471/318057702-b085f486-62b0-4ee5-85b0-4406769cf5e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzQ4NjYsIm5iZiI6MTcxMTkzNDU2NiwicGF0aCI6Ii81MDkzMjQ3MS8zMTgwNTc3MDItYjA4NWY0ODYtNjJiMC00ZWU1LTg1YjAtNDQwNjc2OWNmNWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAxMjI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNWFkYjM4MTVhZWQ2ZWI5Y2IyYWUyYzJhNmFiZTI4ZjQxMzQyMGVjZTIwNTRmZTc4NmJkMDI1MDM0MWJmYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AvITw4zhvNnhk27HUBPpdzGSqkhmDhDdLweWWJhKoT8)

username: android 
password: the rastafarian in you

**Comment by juttflyer** [comment]
> i have problem with login, no info about default credential
> 
> ![image](https://private-user-images.githubusercontent.com/50932471/318057702-b085f486-62b0-4ee5-85b0-4406769cf5e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3ODExNDgsIm5iZiI6MTcxMjc4MDg0OCwicGF0aCI6Ii81MDkzMjQ3MS8zMTgwNTc3MDItYjA4NWY0ODYtNjJiMC00ZWU1LTg1YjAtNDQwNjc2OWNmNWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDIwMjcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyZjY0MjIyOGUxZjM3MWQwNDI0ZjEyMDVhOWU0YTM3NzdiY2EzYWUzNDA3NTJjNmRmYmY4NGI0NDYyNTk5ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nNptBSmgUx1n0PZKI4Qx4z5NaJt0j3RxscCWRPm8LBo)

**The default credentials are** 
username: android
password: the rastafarian in you

**Comment by milier881** [comment]
![KakaoTalk_Snapshot_20240505_175446](https://github.com/Tomiwa-Ot/moukthar/assets/162110251/ccc4dce8-a16e-404d-8dde-30180683d98f)
It’s like shit. None of its functions work. No need to test it. This idiot is a cult propagandist and there is a backdoor.
